TRPZ_PrintService/Pages/EditMIO.cshtml.cs
using System.Linq;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using TRPZ_PrintService.Data;

namespace TRPZ_PrintService.Pages
{
    public class EditMIO : PageModel
    {
        private readonly TRPZ_PrintServiceContext _context;

        public EditMIO(TRPZ_PrintServiceContext context)
        {
            _context = context;
        }

        public SelectList Materials { get; set; }

        public SelectList PostProcessings { get; set; }

        public SelectList Printers { get; set; }
        [BindProperty] public Order order { get; set; }
        public ModelInOrder mio { get; set; }

        [BindProperty] public FormModel Fmodel { get; set; }


        public IActionResult OnGetEdit(int? orderId, int mioid)
        {
            Fmodel = new FormModel();
            mio = _context.ModelsInOrders
                .Include(inOrder => inOrder.Model)
                .Include(inOrder => inOrder.Order)
                .Include(inOrder => inOrder.Material)
                .Include(inOrder => inOrder.Printer)
                .Include(inOrder => inOrder.ModelSettings)
                .Include(inOrder => inOrder.PostProcessing)
                .First(inOrder => inOrder.ModelInOrderId == mioid);

            order = mio.Order;

            Fmodel.Description = mio.Model.Description;
            Fmodel.Layerheight = mio.ModelSettings.LayerHeight;
            Fmodel.Scale = mio.Scale;
            Fmodel.InfillPercentage = mio.ModelSettings.InfillPercentage;
            Fmodel.MaterialId = mio.Material.MaterialId;
            Fmodel.NozzleDiameter = mio.ModelSettings.NozzleDiameter;
            Fmodel.PrinterId = mio.Printer.PrinterId;
            Fmodel.HasSolubleSupports = mio.HasSolubleSupports;
            Fmodel.PostProcessingId = mio.PostProcessing.PostProcessingId;

            Fmodel.Price = mio.PriceTotal;

            Printers = new SelectList(_context.Printers.ToList(), nameof(Printer.PrinterId), nameof(Printer.Name));
            Materials = new SelectList(_context.Materials.ToList(), nameof(Material.MaterialId), nameof(Material.Name));
            PostProcessings = new SelectList(_context.PostProcessings.ToList(), nameof(PostProcessing.PostProcessingId),
                nameof(PostProcessing.Name));

            return Page();
        }

        public IActionResult OnPostEdit(int? orderId, int mioid)
        {
            mio = _context.ModelsInOrders
                .Include(inOrder => inOrder.Model)
                .Include(inOrder => inOrder.Order)
                .Include(inOrder => inOrder.Material)
                .Include(inOrder => inOrder.Printer)
                .Include(inOrder => inOrder.ModelSettings)
                .Include(inOrder => inOrder.PostProcessing)
                .First(inOrder => inOrder.ModelInOrderId == mioid);

            order = mio.Order;

            mio.Model.Description = Fmodel.Description;
            mio.ModelSettings.LayerHeight = Fmodel.Layerheight;
            mio.Scale = Fmodel.Scale;
            mio.ModelSettings.InfillPercentage = Fmodel.InfillPercentage;
            mio.Material = _context.Materials.Find(Fmodel.MaterialId);
            mio.ModelSettings.NozzleDiameter = Fmodel.NozzleDiameter;
            mio.Printer.PrinterId = Fmodel.PrinterId;
            mio.HasSolubleSupports = Fmodel.HasSolubleSupports;
            mio.PostProcessing.PostProcessingId = Fmodel.PostProcessingId;

            mio.PriceTotal = Fmodel.Price;

            // Printers = new SelectList(_context.Printers.ToList(), nameof(Printer.PrinterId), nameof(Printer.Name));
            // Materials = new SelectList(_context.Materials.ToList(), nameof(Material.MaterialId), nameof(Material.Name));
            // PostProcessings = new SelectList(_context.PostProcessings.ToList(), nameof(PostProcessing.PostProcessingId),
            //     nameof(PostProcessing.Name));

            _context.SaveChanges();


            return new RedirectToPageResult("/ModelInOrder", "", new {id = order.OrderId});
        }


        public class FormModel
        {
            public double Scale { get; set; }
            public bool HasSolubleSupports { get; set; }
            public int PostProcessingId { get; set; }
            public string Description { get; set; }

            public int InfillPercentage { get; set; }
            public int Layerheight { get; set; }
            public int NozzleDiameter { get; set; }

            public int PrinterId { get; set; }
            public int MaterialId { get; set; }
            public int Price { get; set; }
        }
    }
}

TRPZ_PrintService/Pages/ManageOrders.cshtml.cs
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using TRPZ_PrintService.Areas.Identity.Data;
using TRPZ_PrintService.Data;

namespace TRPZ_PrintService.Pages
{
    public class ManageOrders : PageModel
    {
        private readonly TRPZ_PrintServiceContext _context;
        private UserManager<TRPZ_PrintServiceUser> _userManager;

        public ManageOrders(TRPZ_PrintServiceContext context, UserManager<TRPZ_PrintServiceUser> userManager)
        {
            _context = context;
            _userManager = userManager;
        }

        public IList<Order> Orders { get; set; }

        public async Task<IActionResult> OnGet(string? type)
        {
            type ??= "all";
            if (type == "unprocessed")
                Orders = await _context.Orders
                    .Include(order => order.Client)
                    .Include(order => order.Models)
                    .ThenInclude(order => order.PostProcessing)
                    .Where(order => order.Status == Order.OrderStatus.Sent ||
                                    order.Status == Order.OrderStatus.Confirmed)
                    .OrderByDescending(order => order.Timestamp)
                    .ToListAsync();
            if (type == "all")
                Orders = await _context.Orders
                    .Include(order => order.Client)
                    .Include(order => order.Models)
                    .ThenInclude(order => order.PostProcessing)
                    .Where(order => order.Status != Order.OrderStatus.NotSent)
                    .OrderByDescending(order => order.Timestamp)
                    .ToListAsync();


            return Page();
        }

        public async Task<IActionResult> OnPostSetStatus(int orderId, string status, string returnUrl)
        {
            var order = _context.Orders.Find(orderId);
            if (status == "not_sent")
                order.Status = Order.OrderStatus.NotSent;
            if (status == "sent")
                order.Status = Order.OrderStatus.Sent;
            if (status == "confirmed")
                order.Status = Order.OrderStatus.Confirmed;
            if (status == "finished")
                order.Status = Order.OrderStatus.Finished;
            if (status == "cancelled")
                order.Status = Order.OrderStatus.Cancelled;


            _context.SaveChanges();
            var a = Request.Headers["Referer"].ToString();
            return Redirect(a);
            // return new RedirectToPageResult("/ManageOrders", "");
        }
    }
}

TRPZ_PrintService/Pages/ManageStaff.cshtml.cs
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using TRPZ_PrintService.Areas.Identity.Data;
using TRPZ_PrintService.Data;

namespace TRPZ_PrintService.Pages
{
    public class ManageStaff : PageModel
    {
        private TRPZ_PrintServiceContext _context;
        private readonly UserManager<TRPZ_PrintServiceUser> _userManager;


        public ManageStaff(TRPZ_PrintServiceContext context, UserManager<TRPZ_PrintServiceUser> userManager)
        {
            _context = context;
            _userManager = userManager;
        }

        public IList<UserRole> UsersRoles { get; set; }

        public async Task<IActionResult> OnGet()
        {
            var users = _userManager.Users.OrderBy(user => user.Id).ToList();
            UsersRoles = new List<UserRole>();

            users.ForEach(user =>
            {
                var r = _userManager.GetRolesAsync(user);
                r.Wait();
                UsersRoles.Add(new UserRole
                {
                    roles = r.Result,
                    user = user
                });
            });

            return Page();
        }

        public async Task<IActionResult> OnPostSetRole(string userId, string role)
        {
            var user = _userManager.Users.First(serviceUser => serviceUser.Id == userId);
            var roles = await _userManager.GetRolesAsync(user);

            if (role == "Admin")
            {
                await _userManager.RemoveFromRoleAsync(user, "Manager");
                await _userManager.AddToRoleAsync(user, "Admin");
            }

            if (role == "Manager")
                // await _userManager.RemoveFromRoleAsync(user, "Admin");
                await _userManager.AddToRoleAsync(user, "Manager");

            if (role == "Client")
            {
                await _userManager.RemoveFromRoleAsync(user, "Admin");
                await _userManager.RemoveFromRoleAsync(user, "Manager");
                await _userManager.AddToRoleAsync(user, "Client");
            }

            return new RedirectToPageResult("/ManageStaff", "");
        }

        public async Task<IActionResult> OnPostDelete(string userId)
        {
            var user = _userManager.Users.First(serviceUser => serviceUser.Id == userId);
            await _userManager.DeleteAsync(user);


            return new RedirectToPageResult("/ManageStaff", "");
        }

        public class UserRole
        {
            public TRPZ_PrintServiceUser user { get; set; }
            public IList<string> roles { get; set; }
        }
    }
}

TRPZ_PrintService/Pages/ModelInOrder.cshtml.cs
using System;
using System.ComponentModel.DataAnnotations;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using TRPZ_PrintService.Data;

namespace TRPZ_PrintService.Pages
{
    public class ModelInOrderPage : PageModel
    {
        private readonly TRPZ_PrintServiceContext _context;
        private readonly IWebHostEnvironment _environment;


        public ModelInOrderPage(TRPZ_PrintServiceContext context, IWebHostEnvironment environment)
        {
            _context = context;
            _environment = environment;
        }

        [BindProperty] public Order order { get; set; }

        [BindProperty] public FormModel Fmodel { get; set; }
        public SelectList Printers { get; set; }

        public SelectList Materials { get; set; }
        public SelectList PostProcessings { get; set; }
        [Required] [BindProperty] public IFormFile Upload { get; set; }

        public IActionResult OnGet(int? id)
        {
            if (id == null) return NotFound();


            order = _context.Orders.Include(order1 => order1.Models)
                .ThenInclude(inOrder => inOrder.Model)
                .Include(order1 => order1.Models)
                .ThenInclude(inOrder => inOrder.ModelSettings)
                .First(order1 => order1.OrderId == id);
            if (order == null) return NotFound();

            Printers = new SelectList(_context.Printers.ToList(), nameof(Printer.PrinterId), nameof(Printer.Name));
            Materials = new SelectList(_context.Materials.ToList(), nameof(Material.MaterialId), nameof(Material.Name));
            PostProcessings = new SelectList(_context.PostProcessings.ToList(), nameof(PostProcessing.PostProcessingId),
                nameof(PostProcessing.Name));

            Fmodel = new FormModel();
            Fmodel.Scale = 100;

            return Page();
        }

        public async Task<IActionResult> OnPostRemove(int id, int mioid)
        {
            var modelInOrder = await _context.ModelsInOrders.FindAsync(mioid);
            _context.ModelsInOrders.Remove(modelInOrder);
            _context.SaveChanges();

            return new RedirectToPageResult("/ModelInOrder", "", new {id});
        }

        public async Task<IActionResult> OnPostCreate(int id)
        {
            order = _context.Orders.Find(id);
            var uploadFileName = Upload.FileName + "_" + DateTime.Now.Ticks;
            var file = Path.Combine(_environment.ContentRootPath, "uploads",
                uploadFileName);
            using (var fileStream = new FileStream(file, FileMode.Create))
            {
                await Upload.CopyToAsync(fileStream);
            }

            var ms = new ModelSettings
            {
                InfillPercentage = Fmodel.InfillPercentage,
                LayerHeight = Fmodel.Layerheight,
                NozzleDiameter = Fmodel.NozzleDiameter
            };

            var m = new Model3D
            {
                Description = Fmodel.Description,
                FilePath = uploadFileName
            };

            var printer = await _context.Printers.FindAsync(Fmodel.PrinterId);
            var material = await _context.Materials.FindAsync(Fmodel.MaterialId);
            var pp = await _context.PostProcessings.FindAsync(Fmodel.PostProcessingId);

            var mio = new ModelInOrder
            {
                Manager = null,
                Material = material,
                Model = m,
                Order = order,
                Printer = printer,
                Scale = Fmodel.Scale,
                ModelSettings = ms,
                PostProcessing = pp,
                HasSolubleSupports = Fmodel.HasSolubleSupports
            };

            order.Models.Add(mio);
            await _context.SaveChangesAsync();

            return new RedirectToPageResult("/ModelInOrder", "", new {id});
        }

        public class FormModel
        {
            public double Scale { get; set; }
            public bool HasSolubleSupports { get; set; }
            public int PostProcessingId { get; set; }
            public string Description { get; set; }

            public int InfillPercentage { get; set; }
            public int Layerheight { get; set; }
            public int NozzleDiameter { get; set; }

            public int PrinterId { get; set; }
            public int MaterialId { get; set; }
        }
    }
}

TRPZ_PrintService/Pages/MyOrders.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using TRPZ_PrintService.Data;

namespace TRPZ_PrintService.Pages
{
    public class MyOrders : PageModel
    {
        private readonly TRPZ_PrintServiceContext _context;

        public MyOrders(TRPZ_PrintServiceContext context)
        {
            _context = context;
        }

        [BindProperty] public List<Order> Orders { get; set; }

        public void OnGet(string? id)
        {
            id ??= User.FindFirstValue(ClaimTypes.NameIdentifier);

            Orders = _context.Orders
                .Include(order => order.Models)
                .ThenInclude(order => order.PostProcessing)
                .Where(order => order.Client.Id == id)
                .OrderByDescending(order => order.Timestamp)
                .ToList();
        }

        public async Task<IActionResult> OnPostSend(string? id, int orderId)
        {
            id ??= User.FindFirstValue(ClaimTypes.NameIdentifier);
            var order = _context.Orders.Find(orderId);
            order.Status = Order.OrderStatus.Sent;
            await _context.SaveChangesAsync();

            return new RedirectToPageResult("/MyOrders", "");
        }

        public async Task<IActionResult> OnPostCancel(string? id, int orderId)
        {
            id ??= User.FindFirstValue(ClaimTypes.NameIdentifier);
            var order = _context.Orders.Find(orderId);
            order.Status = Order.OrderStatus.Cancelled;
            await _context.SaveChangesAsync();

            return new RedirectToPageResult("/MyOrders", "");
        }

        public IActionResult OnPostCreate(string? id)
        {
            id ??= User.FindFirstValue(ClaimTypes.NameIdentifier);

            var order = new Order();
            order.Timestamp = DateTime.Now;
            order.Client = _context.Users.First(user => user.Id == id);

            _context.Orders.Add(order);
            _context.SaveChanges();
            return new RedirectToPageResult("/MyOrders");
        }

        public IActionResult OnPostRemove(string? id, int? orderId)
        {
            var order = _context.Orders.Find(orderId);
            if (order == null) return NotFound();

            try
            {
                _context.Orders.Remove(order);
                _context.SaveChanges();
            }
            catch (Exception e)
            {
                Console.WriteLine(e);
            }

            return new RedirectToPageResult("/MyOrders");
        }
    }
}

TRPZ_PrintService/Pages/OrderManage.cshtml.cs
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace TRPZ_PrintService.Pages
{
    public class OrderManage : PageModel
    {
        public void OnGet()
        {
        }
    }
}

TRPZ_PrintService/Pages/EditMIO.cshtml
@page
@model TRPZ_PrintService.Pages.EditMIO

@{
    Layout = "_Layout";
}

<form asp-page-handler="Edit" asp-route-mioid="@Model.mio.ModelInOrderId" enctype="multipart/form-data">
    <div class="">
        <h4>Edit model</h4>
        @if (User.IsInRole("Manager"))
        {
            <label>Price</label>
            <input class="form-control" type="number" asp-for="Fmodel.Price"/>            <br/>
        }

        <label>Description</label>
        <input class="form-control" type="text" asp-for="Fmodel.Description"/><br/>

        <label>Material</label>
        <select class="form-control" asp-for="Fmodel.MaterialId" asp-items="Model.Materials"></select>
        <br/>

        <label>Printer</label>
        <select class="form-control" asp-for="Fmodel.PrinterId" asp-items="Model.Printers"></select>
        <br/>

        <label>Scale</label>
        <input class="form-control" type="text" asp-for="Fmodel.Scale"/>
        <br/>

        <label>Post-processing</label>
        <select class="form-control" asp-for="Fmodel.PostProcessingId" asp-items="Model.PostProcessings"></select>
        <br/>

        <label>HasSolubleSupports</label>
        <input class="form-control" type="checkbox" asp-for="Fmodel.HasSolubleSupports"/><br/>

    </div>
    <button type="submit" class="btn btn-primary">Apply changes</button>
</form>

TRPZ_PrintService/Pages/ManageStaff.cshtml
@page
@model TRPZ_PrintService.Pages.ManageStaff

@{
    Layout = "_Layout";
}

<table class="table">
    <thead>
    <tr>
        <th>
            Id
        </th>
        <th>
            Name
        </th>
        <th>
            Email
        </th>
        <th>
            Roles
        </th>
        <th>
            &nbsp;
        </th>
    </tr>
    </thead>
    <tbody>
    @foreach (var uRole in Model.UsersRoles)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => uRole.user.Id)
            </td>
            <td>
                @Html.DisplayFor(modelItem => uRole.user.FirstName)
                @Html.DisplayFor(modelItem => uRole.user.LastName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => uRole.user.UserName)
            </td>
            <td>
                @foreach (var role in uRole.roles)
                {
                    @Html.DisplayFor(modelItem => role)
                    <br/>
                }
            </td>
            <td>
                <ul class="list-group">

                    @if (!uRole.roles.Contains("Admin"))
                    {
                        <form asp-page-handler="SetRole" asp-route-userId="@uRole.user.Id" asp-route-role="Admin">
                            <button class="list-group-item list-group-item-action list-group-item-primary" type="submit">Make admin</button>
                        </form>                    }
                    @if (!uRole.roles.Contains("Manager"))
                    {
                        <form asp-page-handler="SetRole" asp-route-userId="@uRole.user.Id" asp-route-role="Manager">
                            <button class="list-group-item list-group-item-action list-group-item-primary" type="submit">Make manager</button>
                        </form>                    }


                    <form asp-page-handler="SetRole" asp-route-userId="@uRole.user.Id" asp-route-role="Client">
                        <button class="list-group-item list-group-item-action list-group-item-primary" type="submit">Make Client</button>
                    </form>


                    <form asp-page-handler="Delete" asp-route-userId="@uRole.user.Id">
                        <button class="list-group-item list-group-item-action list-group-item-danger" type="submit">Delete</button>
                    </form>

                </ul>

            </td>
        </tr>
    }
    </tbody>
</table>

TRPZ_PrintService/Pages/ModelInOrder.cshtml
@page
@using TRPZ_PrintService.Data
@model TRPZ_PrintService.Pages.ModelInOrderPage

@{
    Layout = "Shared/_Layout";
    ViewData["Title"] = "My orders";
}

@{
    var canBeEdited = (Model.order.Status == Order.OrderStatus.NotSent || User.IsInRole("Manager")) && Model.order.Status != Order.OrderStatus.Finished;
}

<h2>Models in order</h2>

<table class="table">
    <thead>
    <tr>
        <th>
            Order ID
        </th>
        <th>
            Material type
        </th>
        <th>
            Has soluble supports
        </th>
        <th>
            Total price
        </th>
        <th>
            File
        </th>
        <th>
            &nbsp;
        </th>
    </tr>
    </thead>
    <tbody>
    @foreach (var mio_model in Model.order.Models)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => mio_model.ModelInOrderId)
            </td>
            <td>
                @Html.DisplayFor(modelItem => mio_model.Material.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => mio_model.HasSolubleSupports)
            </td>
            <td>
                @Html.DisplayFor(modelItem => mio_model.PriceTotal)
            </td>
            <td>
                @Html.DisplayFor(modelItem => mio_model.Model.FilePath)
            </td>
            <td>
                <div class="d-flex">
                    @if (canBeEdited)
                    {
                        <a asp-page="/EditMIO" asp-page-handler="Edit" asp-route-orderid="@Model.order.OrderId" asp-route-mioid="@mio_model.ModelInOrderId" class="ml-2">
                            <button class="btn btn-primary" type="submit">Edit</button>
                        </a>
                        <form asp-page-handler="Remove" asp-route-id="@Model.order.OrderId" asp-route-mioid="@mio_model.ModelInOrderId" class="ml-2">
                            <button class="btn btn-danger" type="submit">Remove</button>
                        </form>                    }
                    else
                    {
                        <button class="btn btn-danger" disabled type="submit" class="ml-2">Remove</button>
                    }
                </div>
            </td>
        </tr>
    }
    </tbody>
</table>

<div class="d-flex">


    @if (canBeEdited)
    {
        <button type="button" class="btn btn-primary" data-toggle="modal" data-target=".bs-modal">
            Add model
        </button>
    }
    @if (Model.order.Status == Order.OrderStatus.NotSent)
    {
        <form asp-page="/MyOrders" asp-page-handler="Send" asp-route-orderId="@Model.order.OrderId" class="ml-2">
            <button type="submit" class="btn btn-primary">
                Send order
            </button>
        </form>    }
    @if (Model.order.Status == Order.OrderStatus.NotSent)
    {
        <form asp-page="/MyOrders" asp-page-handler="Remove" asp-route-orderId="@Model.order.OrderId" class="ml-2">
            <button type="submit" class="btn btn-danger">
                Remove order
            </button>
        </form>    }

    @if (canBeEdited && Model.order.Status != Order.OrderStatus.NotSent)
    {
        <form asp-page="/MyOrders" asp-page-handler="Cancel" asp-route-orderId="@Model.order.OrderId" class="ml-2">
            <button type="submit" class="btn btn-warning">
                Cancel order
            </button>
        </form>    }
    @if (canBeEdited && Model.order.Status == Order.OrderStatus.Sent)
    {
        <form asp-page-handler="SetStatus" asp-route-status="confirmed" asp-route-orderId="@Model.order.OrderId" class="ml-2">
            <button type="submit" class="btn btn-primary">
                Confirm order
            </button>
        </form>    }
    @if (canBeEdited && Model.order.Status == Order.OrderStatus.Confirmed)
    {
        <form asp-page-handler="SetStatus" asp-route-status="finished" asp-route-orderId="@Model.order.OrderId" class="ml-2">
            <button type="submit" class="btn btn-primary">
                Finish order
            </button>
        </form>    }


</div>

<div class="modal fade bs-modal" tabindex="-1" role="dialog" aria-labelledby="myLargeModalLabel" aria-hidden="true">

    <div class="modal-dialog">

        <!-- Modal Content: begins -->
        <div class="modal-content">

            <!-- Modal Header -->
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>

            <!-- Modal Body -->
            <form asp-page-handler="Create" asp-route-id="@Model.order.OrderId" enctype="multipart/form-data">
                <div class="modal-body">
                    <div class="body-message">
                        <h4>Upload model</h4>
                        <label>Description</label>
                        <input class="form-control" type="text" asp-for="Fmodel.Description"/><br/>

                        <label>Material</label>
                        <select class="form-control" asp-for="Fmodel.MaterialId" asp-items="Model.Materials"></select>
                        <br/>

                        <label>Printer</label>
                        <select class="form-control" asp-for="Fmodel.PrinterId" asp-items="Model.Printers"></select>
                        <br/>

                        <label>Scale</label>
                        <input class="form-control" type="number" asp-for="Fmodel.Scale"/>
                        <br/>

                        <label>Post-processing</label>
                        <select class="form-control" asp-for="Fmodel.PostProcessingId" asp-items="Model.PostProcessings"></select>
                        <br/>

                        <label>HasSolubleSupports</label>
                        <input class="form-control form-check" type="checkbox" asp-for="Fmodel.HasSolubleSupports"/><br/>

                        <div class="custom-file">
                            <label class="custom-file-label" for="customFile">.stl File</label>
                            <input type="file" class="custom-file-input" id="customFile" asp-for="Upload">
                        </div>


                    </div>
                </div>

                <!-- Modal Footer -->
                <div class="modal-footer">
                    <button type="button" class="btn btn-primary" data-dismiss="modal">Close</button>
                    <button type="submit" class="btn btn-primary">Add</button>
                </div>
            </form>

        </div>
        <!-- Modal Content: ends -->

    </div>
</div>

TRPZ_PrintService/Pages/MyOrders.cshtml
@page
@using TRPZ_PrintService.Data
@model TRPZ_PrintService.Pages.MyOrders

@{
    Layout = "Shared/_Layout";
    ViewData["Title"] = "My orders";
}

<h2>My orders</h2>

<table class="table">
    <thead>
    <tr>
        <th>
            Order ID
        </th>
        <th>
            Status
        </th>
        <th>
            Price
        </th>
        <th>
            Creation date
        </th>
        <th>
            Models count
        </th>
        <th>
            &nbsp;
        </th>
    </tr>
    </thead>
    <tbody>
    @foreach (var order in Model.Orders)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => order.OrderId)
            </td>
            <td>
                @switch (order.Status)
                {
                    case Order.OrderStatus.NotSent:
                        <span>Not sent</span>
                        break;
                    case Order.OrderStatus.Sent:
                        <span>Sent</span>
                        break;
                    case Order.OrderStatus.Confirmed:
                        <span>Confirmed</span>

                        break;
                    case Order.OrderStatus.Finished:
                        <span>Finished</span>

                        break;
                    case Order.OrderStatus.Cancelled:
                        <span>Cancelled</span>

                        break;
                    default:
                        throw new ArgumentOutOfRangeException();
                }
            </td>
            <td>
                @Html.DisplayFor(modelItem => order.PriceTotal)
            </td>
            <td>
                @Html.DisplayFor(modelItem => order.Timestamp)
            </td>
            <td>
                @Html.DisplayFor(modelItem => order.Models.Count)
            </td>
            <td >
                <div class="d-flex">
                    <a asp-page="/ModelInOrder" asp-route-id="@order.OrderId" class="mr-2">
                        <button class="btn btn-primary">Models</button>
                    </a>
                    @if (order.Status == Order.OrderStatus.NotSent)
                    {
                        <form asp-page-handler="Send" asp-route-orderId="@order.OrderId" class="mr-2">
                            <button class="btn btn-primary" type="submit">Send</button>
                        </form>                    }
                    @if (order.Status == Order.OrderStatus.NotSent)
                    {
                        <form asp-page-handler="Remove" asp-route-orderId="@order.OrderId" class="mr-2">
                            <button class="btn btn-danger" type="submit">Remove</button>
                        </form>                    }
                    @if (order.Status == Order.OrderStatus.Sent)
                    {
                        <form asp-page-handler="Cancel" asp-route-orderId="@order.OrderId" class="mr-2">
                            <button class="btn btn-warning" type="submit">Cancel</button>
                        </form>                    }
                </div>
            </td>
        </tr>
    }
    </tbody>
</table>
@* TODO add modal add window*@
<form asp-page-handler="Create">
    <button type="submit" class="btn btn-primary">
        New Order
    </button>
</form>